### ISSUE TITLE
Improving ideas: analyse constructors + warnings instead of errors

### ISSUE THREAD

**Issue by jmevel** [cezarypiatek/CSharpExtensions#15]
This is a kind ticket just to give you some quick feedback (you asked for it in [your article](https://cezarypiatek.github.io/post/better-non-nullable-handling/)) 

First of all I think the idea of moving the compiler messages to where objects are instanciated is much better than in the declaration of the classes themselves.

So I've tried installing your package for few minutes and there are already some things preventing me from using it in an existing solution at work.

First of all, a required feature (for me) is to be able to analyse what constructors do or if this is not possible just assume the constructor is doing things correctly and is initializing all the non-nullable reference types.

For example let's consider this code:

```csharp
[assembly: InitRequiredForNotNull]

namespace ConsoleApp20
{
    class Program
    {
        static void Main(string[] args)
        {
            new Foo("test");
        }
    }

    public class Foo
    {
        public string Bar { get; set; }

        public Foo(string bar)
        {
            Bar = bar;
        }
    }
}
```

This returns an error saying `Bar` isn't initialized while in fact it is initialized. 
I understand to make this error disappear I just have to declare an empty constructor and instanciate my object like this `new Foo() { Bar ="test" }` however I'd like to bring this Nuget to an existing project and this would be much better if I didn't have to refactor all the code for the sake of making these errors disappear.
I'd like instead to focus on places where there is a REAL risk on non-initalized properties.

My 2nd thought is that by default compile messages should be warnings. Then developers would be free to use the `WarningsAsErrors` feature if they decide they want to be strict about this `CSE001`. 
The thing is, it's not possible to convert an error to a warning (to my knowledge at least).
So in my case that leaves me with an error blocking me unless I refactor my code...

I hope this library will improve, in my opinion this is really how the new nullable reference types feature should natively behave...

Thanks for reading this and thanks also for all your work.

**Comment by cezarypiatek** [comment]
Hi @jmevel

Thank you for your feedback. The idea behind this analyzer is to move the responsibility of initializing members from the type itself to the consumers. Mixing those two approaches: constructors and  `InitRequired` attributes is not recommended. Analyzing what a constructor really does is very complicated and sometimes impossible (when the type is declared outside the source code) and I'm not going even to try to implement it.  If you want to apply CSharpExtension analyzers in the existing solution where some types have constructors then the best idea that comes to my mind is to skip analysis for types with non-default constructors - if you are adding a constructor that means you are taking the responsibility for proper object initialization. I can easily introduce this behavior to the analyzer (maybe it should be configurable). What do you think about it?

Another option for you is to go through all reported places and drop public setter for fields initialized via the constructors.


Regarding to your question about severity level - irregardless what are the defaults, you can always adjust the severity level of given analyzers using ruleset file or editor config with the following entry:

```
[*.cs]

dotnet_diagnostic.CSE001.severity = warning
```

More info about configuring analyzers here https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019

**Comment by jmevel** [comment]
Hi, thanks a lot for your answer.

I added the warning severity in my `.editorconfig` file, I didnt' know we can do that. Good thing to know.

In my specific case some classes are both used with and without a constructor so I can't remove the setters.
Example:

```csharp
public class Foo
{
   public Foo() { }

   public Foo(MyFooModel fooModel)
   {
      if (string.IsNullOrEmpty(fooModel.MyBar))
                throw new ArgumentNullException(nameof(fooModel.MyBar));

      Bar = fooModel.MyBar;
   }

   public string Bar { get; set; }
}
```

So in some parts of the code this class is used like

```csharp
new Foo () { Bar = "test" }
```

and some other places it's instanciated like 

```csharp
new Foo(myFooModel);
```

I think as you said, this would be great to have a configurable way to tell the compiler that with constructors I'm taking full responsibility of correctly setting non-nullable reference types and that the CSE001 shouldn't apply.

What do you think?
If it's easy for you to bring this feature then I'd be really happy to see it coming in a near future.

In the meantime now that I converted CSE001 to warnings I can live with those warnings for the moment and start using your library in our project.

If you're going to implement it, could you please let me know through this ticket when the new version is published?

Thanks again for all your work!

**Comment by cezarypiatek** [comment]
In version 3.0 I disabled checks for initialization block following non-default constructors

**Comment by jmevel** [comment]
Awesome! Thanks a lot for your fast work.
I integrated your package in our solution and used it for the new feature I implemented.
Next sprint I'm gonna solve all warnings on the existing code
