### ISSUE TITLE
Bug(InitOnlyOptional): Missing assignment of default value

### ISSUE THREAD

**Issue by andreas-soroko** [cezarypiatek/CSharpExtensions#22]
i am getting here an error (Missing assignment of default value) but there is a default value ;) 

```csharp
public class TestClass
{
    private string myMember = "default";

    [InitOnlyOptional]
    public string MyMember
    {
        get => myMember;
        set => myMember = string.IsNullOrWhiteSpace(value) ? "default" : value;
    }
}
```

**Comment by cezarypiatek** [comment]
The error is correct, you do not have any initialization which will be invoked during the object creation. You have a default assigned in the `setter` logic, but this logic need to be invoked somehow. Here's one of the solutions:

```cs
    public class TestClass
    {
        [InitOnlyOptional]
        public string MyMember { get; set; } = "default";
    }
```

**Comment by andreas-soroko** [comment]
but this is not the same, 
there is a check in the setter 

`set => myMember = string.IsNullOrWhiteSpace(value) ? "default" : value;` 

maybe is the name `InitOnlyOptional`  a bit misleading
the same code works with `InitOnly` as expected, but the initializer should be optional so i can't use it and thought `InitOnlyOptional` would be right, but `InitOnlyOptional` also requires a default value ( think goes in the same direction as #23 )

so its more an `InitOnlyOptionalWithDefault`

**Comment by cezarypiatek** [comment]
Analyzing setter implementation will complicate the overall solution and will be error-prone. Only automatic properties are supported.
