### ISSUE TITLE
Feature Request(InitOnlyOptional): optional CSE004

### ISSUE THREAD

**Issue by andreas-soroko** [cezarypiatek/CSharpExtensions#23]
Would be great, when CSE004 would be optional. 
We have a linter, that throws errors (don't ask why...) when there is a redundant default value for a property

```csharp
public class TestClass
{
    [InitOnlyOptional]
    public bool MyMember { get; set; } = false;
}
```

**Comment by cezarypiatek** [comment]
That introduces a contradiction here.  ` [InitOnlyOptional]` checks if the values was provided in the field initialization, how should I guess that the value was skipped because it was a default?

**Comment by andreas-soroko** [comment]
Thank you, will check that

**Comment by cezarypiatek** [comment]
You can disable this diagnostic with the following entry in the `.editorconfig` file

```.editorconfig
# CSE004: InitOnlyOptional requires default value
dotnet_diagnostic.CSE004.severity = none
```
