### ISSUE TITLE
TwinType is notifying private field 

### ISSUE THREAD

**Issue by leandromoh** [cezarypiatek/CSharpExtensions#25]
There is a private field `_amount`, with public property `Amount`, on the "source" class.
The attribute is notifying this is not present on "destination" class.  
I would not expected to be notified about private field/properties on "source" class;

error on destination class (class with TwinType attribute):
![image](https://user-images.githubusercontent.com/11452028/102798550-0d27dd00-4390-11eb-9cfd-c36c53aac4c6.png)

source class:
![image](https://user-images.githubusercontent.com/11452028/102798666-2c266f00-4390-11eb-85e6-34da9020655c.png)

**Comment by cezarypiatek** [comment]
Can you provide the whole example? I guess that you are creating an instance within the same type that's why the private field is available through the initialization block.

**Comment by cezarypiatek** [comment]
I've just released a 3.2.81 version that should contains a fix for that Would you mind testing it and letting me know if it works as expected?

**Comment by leandromoh** [comment]
Sorry for the late reply, I checked it again and looks fixed. thanks!
