### ISSUE TITLE
CSSharpExtensions.Annotations Version 3.2.81.0 does not have strong name

### ISSUE THREAD

**Issue by Eric1004** [cezarypiatek/CSharpExtensions#27]
Hello,

I currently use Version 3.2.81 in an .NET 5 project where I can not build on release, because I get following error:

`4>CSC : error CS8002: Referenced assembly 'CSharpExtensions.Annotations, Version=3.2.81.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

Best Regards

**Comment by cezarypiatek** [comment]
Non of my packages have stron names. I need to figure out how to fix it

**Comment by Eric1004** [comment]
That would be great, thanks a lot!

**Comment by cezarypiatek** [comment]
Ok, After 3.5h I've managed to build and publish package with strongly named assemblies. @Eric1004, would you mind trying to install v3.3.0 and letting me know if that works for you?

**Comment by Eric1004** [comment]
Works like a charm, thanks a lot again!
