### ISSUE TITLE
ReturnValueUnusedAnalyzer: add support for Disabling analyzer

### ISSUE THREAD

**Issue by Lonli-Lokli** [cezarypiatek/CSharpExtensions#39]
Use case - within test projects.

**Comment by cezarypiatek** [comment]
Hi @Lonli-Lokli 

You can add `.editorconfig` on the test project level and override your global settings with the following entry

```
dotnet_diagnostic.CSE005.severity = none
```

Please let me know if that works for you

**Comment by Lonli-Lokli** [comment]
Thanks, it works.
