### ISSUE TITLE
CS8618 being cleared from non default constructors

### ISSUE THREAD

**Issue by vsilvar** [cezarypiatek/CSharpExtensions#48]
Given `SkipWhenConstructorUsed` is `true` and the following code:
```c#
using SmartAnalyzers.CSharpExtensions.Annotations;

[assembly: InitRequiredForNotNull]
namespace AnalyzerTest
{
    class Program
    {
        static void Main()
        {
            _ = new Person()
            {
                Name = "Foo",
                Age = 18
            };
        }
    }

    class Person
    {
        public string Name { get; set; }
        public int Age { get; set; }

        public Person(){}

        public Person(object somethingElse)
        {
            //Name = somethingElse as string ?? "Foo";
        }
    }
}
```

I would expect to receive the following warning in line 25:
`CS8618 - Non-nullable property 'Name' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.`

As I would expect that only the default constructor is "affected" by this analyzer.
The current behavior is fine if `SkipWhenConstructorUsed` is `false`, as there I expect all constructors to be affected.

**Comment by cezarypiatek** [comment]
The following attributes ` [InitRequired]`, `[InitOnly]` and [`InitRequiredForNotNull]` are intended to replace the constructors and you shouldn't mix that two approaches. Right now the `Suppressor` responsible for discarding `CS8618` works without taking into account the context - it simply discards all `CS8618` within the assembly that was marked with `[InitRequiredForNotNull]`.

I can change this behavior but I'm not sure if your interpretation will be obvious for other users. My recommendation is to replace this kind of mapping constructor with a static factory method.

**Comment by vsilvar** [comment]
I think using a static factory method makes total sense, and indeed solves the issue.
