### ISSUE TITLE
Improve handling of init only with constructor?

### ISSUE THREAD

**Issue by jhf** [cezarypiatek/CSharpExtensions#53]
We are using records (that are immutable) in our source code, using the constructor syntax.

From the C# 9  blog https://devblogs.microsoft.com/dotnet/c-9-0-on-the-record/

For example:

```
public record Person(string FirstName, string LastName); 
```
Where  it can be used as `new Person("Mads", "Torgersen");`

I.e. using a shorthand both for declaring and using a compact type.

The problem appears when using
```
global using SmartAnalyzers.CSharpExtensions.Annotations;
[assembly: InitRequiredForNotNull]
```

Then `new Person("Mads", "Torgersen");` will not be allowed, as it is not properly initialising the properties. So one could try to use
```
Person {
FirstName = "Mads",
LastName = "Torgersen"
};
```
But that will fail, because there is not constructor that takes 0 arguments.

In our project we have then annotated these records with `[InitOptional]`- since they can only be instantiated with a constructor using the appropriate number of arguments.

```
[InitOptional]
public record Person(string FirstName, string LastName); 
```

However, it would have been nice if this could have been discovered by the tool itself, and no such annotation was required.

**Comment by cezarypiatek** [comment]
Hi @jhf 

Thanks for reporting this issue. So the expected behavior is to exclude record types from this analysis, correct?

**Comment by jhf** [comment]
@cezarypiatek You are correct, I followed the recipe for setup of a global attribute, and added the suggested `CSharpExtensions.json` with

```
{
  "CSE001": {
    "SkipWhenConstructorUsed": false
  },
  "CSE005": {
    "IgnoredReturnTypes": [
      "Microsoft.Extensions.DependencyInjection.IServiceCollection",
      "Microsoft.Extensions.Configuration.IConfigurationBuilder",
      "Microsoft.Extensions.Logging.ILoggingBuilder"
    ]
  }
}
```

Changing this fixed the issue.

Why do you suggest starting with `"SkipWhenConstructorUsed": false`?
