### ISSUE TITLE
[Proposal] TwinType support for enums

### ISSUE THREAD

**Issue by rafalschmidt97** [cezarypiatek/CSharpExtensions#59]
First of all, I must say I love this NuGet - especially `InitRequiredForNotNullAttribute` and that I can just annotate everything with:

```xaml
  <ItemGroup>
    <AssemblyAttribute Include="SmartAnalyzers.CSharpExtensions.Annotations.InitRequiredForNotNullAttribute" />
  </ItemGroup>
```

It makes C# NRT feature truly useful. Thank you very much for this contribution!

---

Recently I've been playing with the `TwinTypes` attribute and as cool as it is, for me it lacks the support for enums. 

After a bit of research, I've even found people writing a custom test cases to fill the gap

```csharp
    [Fact]
    public void CheckEnumFields()
    {
        CheckEnumEqualFields<DataContracts.TestEnumReason, Domain.TestEnumReason>();
    }
    private static void CheckEnumEqualFields<TEnum1, TEnum2>()
    {
        var enumNames1 = Enum.GetNames(typeof(TEnum1));
        var enumNames2 = Enum.GetNames(typeof(TEnum2));
        enumNames1.Should().BeEquivalentTo(enumNames2);
    }
```

I was wondering if you are planning to add it. What do you think?

**Comment by cezarypiatek** [comment]
Thanks for the feedback. I've never thought about using TwinTypes for enum but it totally makes sense.
I will try to add this feature

**Comment by cezarypiatek** [comment]
I've just released a new version containing the requested feature.  Not sure how the codefix should work, especially in terms of members' order and values. I added a simple and naive version that appends missing members at the end.

Would you mind testing it and letting me know if that works fine for you?

**Comment by rafalschmidt97** [comment]
Works like a charm :) It doesn't check the order but as long as the serialisation is based on names instead of numbers it does the job. Thank you!
