### ISSUE TITLE
Analyzer is unable to detect never awaited tasks which are asigned to any variable

### ISSUE THREAD

**Issue by suchoss** [cezarypiatek/CSharpExtensions#62]
I expected that the CSE008 would be able to find Task assigned to variable but still never awaited. Current behavior is like with CS4014.

![image](https://user-images.githubusercontent.com/39336141/181712846-f2501826-8741-4d0c-a8e1-ef6da3a502a9.png)

[I've created simple project which illustrates the issue.](https://github.com/suchoss/AsyncTaskAnalyzer/blob/master/AsyncTaskAnalyzerTest/Test.cs)

**Comment by cezarypiatek** [comment]
I created another analyzer `CSE009: Task variable not awaited` to address this issue.
It's reported for every `Task` and `Task[]` local variable (ValueTask handled respectively) when
- there's no `await` expression
- there's no `Wait()` and `GetAwaiter()` call
- it's not an argument for any method's call
- it's not returned from the method
- it's not a subject of cast operation
- it's not the right-hand operand of the assignment operation

Definitely, there are more use cases when this issue should not be reported. If you find any, please let me know.
I will appreciate any feedback regarding this initial implementation.

**Comment by suchoss** [comment]
@cezarypiatek Thanks. It works perfectly! So far I didn't found a case where it shouldn't be reported. But If I find any, I will report it.

I am closing the issue.
