### ISSUE TITLE
CSE007 possible incorrect analysis

### ISSUE THREAD

**Issue by suchoss** [cezarypiatek/CSharpExtensions#64]
It seems to me, that `responseMessage.EnsureSuccessStatusCode();` is falsely triggering CSE007.

But maybe I do not understand how to properly dispose response message. I tried to use finally block as well with manual disposal, but it still doesn't work. 

![image](https://user-images.githubusercontent.com/39336141/209331440-a0cd2155-a8ac-4974-a7c4-08120b4281cd.png)

```c#
private static async Task DownloadFileAsync<T>(HttpClient httpClient,
            string url,
            string path) 
        {
            using var responseMessage = await _retryPolicy.ExecuteAsync(() => httpClient.GetAsync(url, HttpCompletionOption.ResponseHeadersRead));

            try
            {
                responseMessage.EnsureSuccessStatusCode();


                var stream = await responseMessage.Content.ReadAsStreamAsync();
                using var fileStream = File.Open(path, FileMode.Create);

                await stream.CopyToAsync(fileStream);
                await fileStream.FlushAsync();
            }
            catch (Exception e)
            {
                Consts.Logger.Error($"Url: {url} can not process stream properly.", e);
                throw;
            }
            finally
            {
                responseMessage.Dispose();
            }
            
        }
```

**Comment by cezarypiatek** [comment]
Hi @suchoss,
Thanks for reporting this issue. This is a typical problem with  (sloppily designed) fluent interfaces. The `EnsureSuccessStatusCode`  method returns `HttpResponseMessage` instance (there's `return this` inside) hence the reported diagnostic. The best option here is to explicitly discard the method result:

```cs
_ = responseMessage.EnsureSuccessStatusCode();
```

or you can chain the method call to fulfill author expectations:

```cs
var stream = await responseMessage.EnsureSuccessStatusCode().Content.ReadAsStreamAsync();
```

The CSE007 diagnostic behaves as it is expected.

**Comment by suchoss** [comment]
Hi @cezarypiatek Thanks for the info! I will keep this in mind.
