### ISSUE TITLE
Proposal: custom constructors handling

### ISSUE THREAD

**Issue by ewancoder** [cezarypiatek/CSharpExtensions#7]
I think it's a good idea to implement custom constructor support (and analysis). For example, I want the following behavior to work as expected:

```
    [InitRequired]
    public class Address
    {
        // Default constructor should NOT report CS8618 (since we are using InitRequired).
        public Address() { }

        // This constructor SHOULD report CS8618 (since it doesn't set all non-nullable fields).
        // Even though we have InitRequired attribute set.
        public Address(string city)
        {
            City = city;
        }

        // This constructor should NOT report CS8618 (since it initializes the object in a valid state).
        public Address(string city, bool hasStreet)
        {
            City = city;
            Street = hasStreet ? "Default avenue" : "Unknown";
        }

        public string City { get; set; }
        public string Street { get; set; }
        public string? SecondAddress { get; set; }
    }

    static class Program
    {
        static void Main()
        {
            // CSE001: Missing initialization of all 3 fields.
            var message = new Address();

            // CSE001: Missing initialization of 2 fields.
            var message2 = new Address
            {
                City = "city"
            };

            // Constructor should handle object being properly initialized.
            // Allow custom constuctors here, do NOT report CSE001.
            var message3 = new Address("city");
        }
    }
```

**Comment by ewancoder** [comment]
I'm not very good at Roslyn, in fact I just started learning it to tweak this amazing set of analyzers to my liking. This is what I came up with so far: just disabling initializer analysis when we've got a custom constructor.

https://github.com/ewancoder/CSharpExtensions/commit/899b34610b478dddafae0e4d6e0be35dafc5f883

I'm thinking about also suppressing CS8618 on default empty constructor and that should be it, since CS8618 is still going to be present on all non-default constructors thus forcing us to implement constructors so they set the object in completely valid state.

**Comment by ewancoder** [comment]
It might be an interesting idea to try to make sure that the object is initialized in correct state at the end of initialization so part of it can be initialized in custom constructor and the rest is using initializer, but that sounds difficult to me, that's why I came up with easier idea.

Right now when we create an object with a custom constructor - the analyzer still forces us to use initializer and to initialize all the fields.

**Comment by ewancoder** [comment]
This will leave CS8618 for custom constructors https://github.com/ewancoder/CSharpExtensions/commit/2359855fa6ce66fdfc99ec3bc45a9c6a5ca0084c

**Comment by cezarypiatek** [comment]
@ewancoder thanks for raising this issue. Right now I am super busy, I hope I wil have tame to take a look at that next week.

**Comment by cezarypiatek** [comment]
It's really hard to determine if a given constructor provides values for all required fields. When the type is defined outside the source code this is completely impossible. You should not mix `[InitRequired]` attribute with custom constructors - it will result with unnecessary complexity. The idea behind this attribute is to replace custom constructors with initialization blocks.

**Comment by ewancoder** [comment]
I was thinking we could let compiler decide if the constructor initialized object correctly (by default if we don't initialize some non-nullable reference field then we see a warning/error from NullableRefenence type analysis).

**Comment by ewancoder** [comment]
But yeah I guess I could go with static methods that create a new object by using initializer. What I want to achieve is to create a class that is serializable by serialization engines (JSON or some kind of ORM etc) but provide convenient way for client to create the instances of these objects.

**Comment by Lonli-Lokli** [comment]
@cezarypiatek Does it makes sense to create Autofix (similar to Resharper suggestions) to replace custom constructor with full initialization block?
Currently we have failing class, widely used, with custom constructor - and it does not produce any error.

**Comment by cezarypiatek** [comment]
Sounds interesting but non-trivial to implement - it's not easy to guess which constructor parameter is responsible for initializing a given field/property. Any ideas or suggestions for that loggic?

**Comment by Lonli-Lokli** [comment]
Im not too familiar with generators, actually, so here I'm just because I have few types with custom constructors, difficult to update in so many places.

**Comment by cezarypiatek** [comment]
Do constructor parameter names match the property names? If so, we can apply this kind of heuristic for the codefix.

**Comment by Lonli-Lokli** [comment]
In our case they differs just by case

**Comment by cezarypiatek** [comment]
Can you provide a few examples?

**Comment by Lonli-Lokli** [comment]
In our case the simplest and widely used is this one

```
    class Program
    {
        static void Main(string[] args)
        {
            var owner = new Owner(1, "test");
        }

        [InitOnly]
        public class Owner
        {
            public int Id { get; }
            public string Name { get; }
            public string Address { get; set; } = string.Empty;
            public string Email { get; set; }
            public bool IsAtive { get; set; }

            public Owner(int id, string name)
            {
                Id = id;
                Name = name;
            }
        }
    }
```

**Comment by cezarypiatek** [comment]
It looks like this one has matching constructor argument names to property names. I can make a code fix that will try to rewrite it into init block.

**Comment by Lonli-Lokli** [comment]
It will be great, thanks! Is it possible to make it project-level fix, of it's a Resharper-only feature?

**Comment by cezarypiatek** [comment]
After a couple of hours, I managed to create such codefix. However,  `CSE001` is not reported when the constructor invocation is used -  to avoid breaking changes I introduced a configuration for  `CSE001` that allows changing that behavior.  Regarding to your last question - yes, it's possible to execute that fix for all occurrences of `CSE001 at once. For more details, please take a look at the section in readme **"Migrating from Constructors to Initialization Blocks" **https://github.com/cezarypiatek/CSharpExtensions#migrating-from-constructors-to-initialization-blocks

Please let me know if that code fix is working for you as you expected.

**Comment by cezarypiatek** [comment]
@Lonli-Lokli did you have a chance to look into this?

**Comment by Lonli-Lokli** [comment]
@cezarypiatek sorry it didnot work for my project and I was too lazy to crereate sample for you
Can you look into this?
https://github.com/Lonli-Lokli/constructor_init

Also mb you know, if this Project refactoring available in Rider? One of my colleagues has only Rider and this extensions for bulk change do not work

**Comment by Lonli-Lokli** [comment]
As you probably see, first apply creates invalid code, second - created another version and loose actual parameters.

**Comment by cezarypiatek** [comment]
I guess that you are expecting that Id and UserId will be appropriately assigned. It's not working because they don't have public setters.

**Comment by Lonli-Lokli** [comment]
So before making this migration I have to add setters (which is safe as we have InitOnly), right? Will check tomorrow!

**Comment by cezarypiatek** [comment]
1) Yes, you need to add publicly available setters
2) I've just checked your solution in JetBrains Rider and the CodeFix works fine
![image](https://user-images.githubusercontent.com/7759991/116152874-c6077b00-a6e6-11eb-9bc8-92fa2abce8c5.png)

**Comment by Lonli-Lokli** [comment]
2. Yes, it is available in Rider but only for one line, not for the project or solution.

**Comment by Lonli-Lokli** [comment]
@cezarypiatek Thank you, it works!
