### ISSUE TITLE
Multitarget netstandard2.0

### ISSUE THREAD

**Issue by Arithmomaniac** [cezarypiatek/CSharpExtensions#8]
From https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#net-standard (emphasis mine)

> ❌ AVOID including a netstandard1.x target.
> 
> .NET Standard 1.x is distributed as a granular set of NuGet packages, which **creates a large package dependency graph and results in developers downloading a lot of packages when building**. Modern .NET platforms, including .NET Framework 4.6.1, UWP and Xamarin, all support .NET Standard 2.0. You should only target .NET Standard 1.x if you specifically need to target an older platform.
> 
> ✔️ **DO include a netstandard2.0 target** if you require a netstandard1.x target.
> 
> All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.x target.

I ran into this adding the analyzers to a net472 project.

**Comment by cezarypiatek** [comment]
Hi,

I read this excerpt from the design guideline a couple of times and don't understand the problem.  Analyzers and their dependencies should not be copied to the application/library output directory. Package with the annotations has no dependencies and I made it netstandard 1.x to make it more versatile - you should be able to use it with any kind of the projects.

**Comment by Arithmomaniac** [comment]
The problem is described in this Stackoverflow question:
https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies/
Multi-targeting to fix it usually only requires a one line change to the
csproj file (not at my desk ATM)

**Comment by cezarypiatek** [comment]
Released SmartAnalyzers.CSharpExtensions.Annotations.2.3.52 as a multi-target package. Please let me know if that solved the issue.

**Comment by Arithmomaniac** [comment]
Confirmed. Thanks!
