### ISSUE TITLE
Add "optional immutable members" attribute

### ISSUE THREAD

**Issue by Arithmomaniac** [cezarypiatek/CSharpExtensions#9]
There can be cases where an immutable property has a default value, but can't be modified after. For example:

```csharp
class Finance
{
    readonly int profit;
    public Finance(int Profit = 45) { profit = Profit; }
}
```

There is no way to enforce this using `InitOnly` at the moment, because `InitOnly` requires specification in the construction analyzer.

Something like the following would be nice:

```csharp
class Finance
{
    [InitOnlyOptional]
    int Profit { get; set; } = 45;
}
```

**Comment by cezarypiatek** [comment]
Hi @Arithmomaniac 

I've just released SmartAnalyzers.CSharpExtensions.Annotations.2.2.49 with InitOnlyOptional attribute. This analyzers for this new attribute verify if:
- property/field  declaration provides a default value
- property/field is not modified outside the initialization block

Can you test it and let me know if it works as you expected?

**Comment by Arithmomaniac** [comment]
Confirmed. Thanks!
